/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RetweetRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.RetweetRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1477550228;

	/**
	 * Setter for <code>public.retweet.tweet_id</code>.
	 */
	public void setTweetId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.retweet.tweet_id</code>.
	 */
	public java.lang.Long getTweetId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.retweet.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.retweet.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return tech.codingclub.helix.tables.Retweet.RETWEET.TWEET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return tech.codingclub.helix.tables.Retweet.RETWEET.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getTweetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetweetRecord value1(java.lang.Long value) {
		setTweetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetweetRecord value2(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetweetRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RetweetRecord
	 */
	public RetweetRecord() {
		super(tech.codingclub.helix.tables.Retweet.RETWEET);
	}

	/**
	 * Create a detached, initialised RetweetRecord
	 */
	public RetweetRecord(java.lang.Long tweetId, java.lang.Long userId) {
		super(tech.codingclub.helix.tables.Retweet.RETWEET);

		setValue(0, tweetId);
		setValue(1, userId);
	}
}
