/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Retweet extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.RetweetRecord> {

	private static final long serialVersionUID = 1735934864;

	/**
	 * The singleton instance of <code>public.retweet</code>
	 */
	public static final tech.codingclub.helix.tables.Retweet RETWEET = new tech.codingclub.helix.tables.Retweet();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.RetweetRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.RetweetRecord.class;
	}

	/**
	 * The column <code>public.retweet.tweet_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.RetweetRecord, java.lang.Long> TWEET_ID = createField("tweet_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.retweet.user_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.RetweetRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.retweet</code> table reference
	 */
	public Retweet() {
		this("retweet", null);
	}

	/**
	 * Create an aliased <code>public.retweet</code> table reference
	 */
	public Retweet(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Retweet.RETWEET);
	}

	private Retweet(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.RetweetRecord> aliased) {
		this(alias, aliased, null);
	}

	private Retweet(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.RetweetRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.RetweetRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.RetweetRecord>>asList(tech.codingclub.helix.Keys.UNIQUE_CONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.RetweetRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<tech.codingclub.helix.tables.records.RetweetRecord, ?>>asList(tech.codingclub.helix.Keys.RETWEET__FOREIGN_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Retweet as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Retweet(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Retweet rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Retweet(name, null);
	}
}
